version: "3.9"

volumes:
  e-commerce_data:

services:
  e-commerce-app:
    build: ./
    command: ./app
    ports:
      - "8586:8586"
    volumes:
      - .:/src
    environment:
      - GONOSUMDB=off
      - TZ=Asia/Almaty
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:13.2-alpine
    volumes:
      - e-commerce_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5436:5432
